#from gensim import corpora, models, similarities
import logging
import sys
import os
import io
import spacy
import nltk
import gensim
from pprint import pprint
from gensim import corpora, models, similarities
from collections import defaultdict
import pyLDAvis
import pyLDAvis.gensim  # don't skip this
import matplotlib.pyplot as plt


'''
# Analyse docs using Gensim library to Analyse topics based on pre-built corpus\
# based on https://radimrehurek.com/gensim/tut2.html
'''

# Main

# Set Logging level
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)


# Check for and display usage message
# run .\scripts\smart_analyse_gensim_topics.py .\output\output.dict .\output\output.corpus


if (len(sys.argv)!=3):    # arg 0 is script name
    print("\n=====")
    print("Smart")
    print("=====\n")
    print("Analyse topics based on pre-built corpus\n")
    print("Usage:")
    print("python wip_gensim.py name_of_dictionary.dict name_of_corpus.corpus")
    sys.exit()

#Load Args into variables
name_of_dictionary = sys.argv[1]
name_of_corpus=sys.argv[2]

# Load files generated by smart_dict.py
print("Loading previously generated Dictionary:"+name_of_dictionary)
smart_dictionary = corpora.Dictionary.load_from_text(name_of_dictionary)
print("Loading previously Corpus:"+name_of_corpus)
smart_corpus = corpora.MmCorpus(name_of_corpus)

#Give a boost to less frequently used words
smart_tfidf = models.TfidfModel(smart_corpus)

# initialize an ldi  transformation
#lsi = models.LsiModel(smart_corpus, id2word=smart_dictionary, num_topics=300)
lda = models.LdaModel(smart_corpus, id2word=smart_dictionary, num_topics=300)
#corpus_lsi = lsi[smart_tfidf] # create a double wrapper over the original corpus: bow->tfidf->fold-in-lsi

print('\nPerplexity: ', lda.log_perplexity(smart_corpus))
vis = pyLDAvis.gensim.prepare(lda, smart_corpus, smart_dictionary)
vis


##### next https://radimrehurek.com/gensim/tut2.html - try transformation
##### start at Transformations can also be serialized
##### extract and list topics, some html page or XL to interact (filename)