# Bit hacky, but run the python script multiple times to ensure all files are downloaded
# avoids a memory leak in the python script
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
python3 download.py
